version: "3.8"
services:
  web-server:
    container_name: tend
    restart: always
    build: .
    command: npm run start:dev
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "3000:3000"
